steps:
  - name: 'golang:1.22'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        go mod tidy
        go test ./...
        GOOS=linux GOARCH=amd64 go build -o main .

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cr-vs-gke/my-devops-app:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/cr-vs-gke/my-devops-app:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'my-cloud-run-service', '--image', 'gcr.io/cr-vs-gke/my-devops-app:latest', '--region', 'us-central1', '--platform', 'managed']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['kubectl', 'set', 'image', 'deployment/my-gke-deployment', 'my-container=gcr.io/cr-vs-gke/my-devops-app:latest', '--namespace=default']

images:
  - 'gcr.io/cr-vs-gke/my-devops-app:latest'

logs_bucket: 'gs://my-logs-bucket'
