steps:
  - name: 'golang:1.22'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        go mod tidy
        go test ./...
        GOOS=linux GOARCH=amd64 go build -o main .

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cr-vs-gke/my-devops-app-gke:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/cr-vs-gke/my-devops-app-gke:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['kubectl', 'apply', '-f', 'deployment.yaml']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['kubectl', 'apply', '-f', 'service.yaml']

images:
  - 'gcr.io/cr-vs-gke/my-devops-app-gke:latest'

logs_bucket: 'gs://my-logs-bucket98'
