steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cr-vs-gke/my-devops-app-gke:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/cr-vs-gke/my-devops-app-gke:latest']

  # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=kubernetes/deployment.yaml
      - --location=us-central1-a
      - --cluster=my-gke-cluster

options:
  logging: CLOUD_LOGGING_ONLY
