steps:
  - name: 'golang:1.22'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        go mod tidy
        go test ./...
        GOOS=linux GOARCH=amd64 go build -o main .

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cr-vs-gke/my-devops-app-gke:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/cr-vs-gke/my-devops-app-gke:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['kubectl', 'set', 'image', 'deployment/my-devops-app-gke-deployment', 'my-devops-app-gke=gcr.io/cr-vs-gke/my-devops-app-gke:latest', '--namespace=default']

images:
  - 'gcr.io/cr-vs-gke/my-devops-app-gke:latest'

options:
  logging: CLOUD_LOGGING_ONLY
